server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://webidetesting4757575-fiori.dispatcher.int.sap.eu2.hana.ondemand.com"
            allowedMethods:
              - GET

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
